import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import {
    VContainer,
    VRow,
    VCol,
    VTooltip,
    VBtn,
    VIcon,
    VList,
    VListItem,
    VListItemAction,
    VListGroup,
    VListItemContent,
    VListItemTitle,
    VCard,
    VCardTitle,
    VCardText,
    VMenu,
    VToolbar,
    VToolbarTitle,
    VSpacer,
    VForm,
    VTextField,
    VCardActions,
    VCheckbox,
    VSimpleTable,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VDialog,
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VContainer,
        VRow,
        VCol,
        VTooltip,
        VBtn,
        VIcon,
        VList,
        VListItem,
        VListItemAction,
        VListGroup,
        VListItemContent,
        VListItemTitle,
        VCard,
        VCardTitle,
        VCardText,
        VMenu,
        VToolbar,
        VToolbarTitle,
        VSpacer,
        VForm,
        VTextField,
        VCardActions,
        VCheckbox,
        VSimpleTable,
        VExpansionPanels,
        VExpansionPanel,
        VExpansionPanelHeader,
        VExpansionPanelContent,
        VDialog,
    }
});

const opts = {};

export default new Vuetify(opts)
